id: P7E5664CE
initial_creation_type: input
source_metadata:
  title: Sherab Özer Series
  language: bo
  description: 'Texts by and about Trengpo Tertön Sherab Özer (''phreng po gter ston
    shes rab ''od zer, 1518–1584) alias Drodül Lingpa:'
  volume:
    5b0d0c37fcac4a2fbf5c16856f243ce8:
      title: Dispeller of All Samaya Corruptions and Pollutions
      parent: Damdrip Nyepa Kunsel
    4fb5a7a2bbd9414ca6de1b0a5576c402:
      title: 'Moonlight of Pacifying Amṛta: A Daily Visualization and Recitation for
        the Dispeller of All Samaya Corruptions and Pollutions'
      parent: Sādhanas
created_at: '2022-03-01T01:36:54.057816'
last_modified_at: '2022-03-01T01:36:54.057818'
statistics:
  total_words: 1605
  total_non_words: 315
quality:
  non_words_ratio: 0.2
